"""DOCX exporter using python-docx."""

from __future__ import annotations

from pathlib import Path

from forgereport.core.parser import ParsedReport, parse_report

SEVERITY_COLORS = {
    "critical": "C00000",
    "high": "F4A100",
    "medium": "FFD966",
    "low": "3D85C6",
}


def export_docx(markdown: str, output_path: str | Path) -> Path:
    from docx import Document
    from docx.enum.text import WD_BREAK

    parsed = parse_report(markdown)
    path = Path(output_path)
    document = Document()

    _add_cover_page(document, parsed)
    _add_footer(document, parsed)
    document.add_paragraph().add_run().add_break(WD_BREAK.PAGE)

    if parsed.findings:
        document.add_heading("Findings Overview", level=1)
        _add_findings_table(document, parsed)

    _add_markdown_body(document, parsed.body)
    document.save(path)
    return path


def _add_cover_page(document, parsed: ParsedReport) -> None:
    document.add_heading(parsed.title, level=0)
    meta = parsed.metadata
    details = [
        ("Target", meta.get("target", "")),
        ("Date", meta.get("date", "")),
        ("Mode", meta.get("mode", "")),
        ("Difficulty", meta.get("difficulty", "")),
    ]
    for label, value in details:
        paragraph = document.add_paragraph()
        paragraph.add_run(f"{label}: ").bold = True
        run = paragraph.add_run(str(value or ""))
        if label == "Difficulty":
            run.bold = True


def _add_footer(document, parsed: ParsedReport) -> None:
    for section in document.sections:
        paragraph = section.footer.paragraphs[0]
        paragraph.text = f"Generated by ForgeReport | {parsed.metadata.get('date', '')}"


def _add_findings_table(document, parsed: ParsedReport) -> None:
    table = document.add_table(rows=1, cols=4)
    table.style = "Table Grid"
    headers = ["Name", "Severity", "CVE", "Description"]
    for idx, header in enumerate(headers):
        table.rows[0].cells[idx].text = header
    for finding in parsed.findings:
        cells = table.add_row().cells
        cells[0].text = finding.name
        severity_run = cells[1].paragraphs[0].add_run(finding.severity)
        color = SEVERITY_COLORS.get(finding.severity.lower())
        if color:
            from docx.shared import RGBColor

            severity_run.font.color.rgb = RGBColor.from_string(color)
            severity_run.bold = True
        cells[2].text = finding.cve
        cells[3].text = finding.description


def _add_markdown_body(document, body: str) -> None:
    in_code = False
    code_lines: list[str] = []
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            if in_code:
                _add_code_block(document, "\n".join(code_lines))
                code_lines = []
                in_code = False
            else:
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        if not stripped:
            continue
        if stripped.startswith("### "):
            document.add_heading(stripped[4:], level=3)
        elif stripped.startswith("## "):
            document.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            document.add_heading(stripped[2:], level=1)
        elif stripped.startswith("- "):
            _add_bullet(document, stripped[2:])
        else:
            document.add_paragraph(stripped)
    if code_lines:
        _add_code_block(document, "\n".join(code_lines))


def _add_bullet(document, text: str) -> None:
    paragraph = document.add_paragraph(style="List Bullet")
    run = paragraph.add_run(text)
    if text.lower().startswith("severity:"):
        severity = text.split(":", 1)[1].strip().lower()
        color = SEVERITY_COLORS.get(severity)
        if color:
            from docx.shared import RGBColor

            run.font.color.rgb = RGBColor.from_string(color)
            run.bold = True


def _add_code_block(document, code: str) -> None:
    from docx.shared import Pt

    paragraph = document.add_paragraph()
    _shade_paragraph(paragraph, "EFEFEF")
    run = paragraph.add_run(code or " ")
    run.font.name = "Courier New"
    run.font.size = Pt(9)


def _shade_paragraph(paragraph, fill: str) -> None:
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    p_pr = paragraph._p.get_or_add_pPr()
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), fill)
    p_pr.append(shading)
