"""PDF exporter using WeasyPrint."""

from __future__ import annotations

import html
import re
from pathlib import Path

from forgereport.core.parser import parse_report


def export_pdf(markdown: str, output_path: str | Path) -> Path:
    try:
        from weasyprint import HTML
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "WeasyPrint is not installed. Run `pip install -r requirements.txt` and ensure "
            "WeasyPrint system dependencies are available."
        ) from exc

    parsed = parse_report(markdown)
    body_html = markdown_to_html(parsed.body)
    meta = parsed.metadata
    document_html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>{html.escape(parsed.title)}</title>
  <style>{PDF_CSS}</style>
</head>
<body>
  <section class="cover">
    <div class="brand">ForgeReport</div>
    <h1>{html.escape(parsed.title)}</h1>
    <p>Raw input. Professional output.</p>
    <dl>
      <dt>Target</dt><dd>{html.escape(str(meta.get("target", "")))}</dd>
      <dt>Date</dt><dd>{html.escape(str(meta.get("date", "")))}</dd>
      <dt>Mode</dt><dd>{html.escape(str(meta.get("mode", "")))}</dd>
      <dt>Difficulty</dt><dd>{html.escape(str(meta.get("difficulty", "")))}</dd>
    </dl>
  </section>
  <main>{body_html}</main>
</body>
</html>"""
    path = Path(output_path)
    HTML(string=document_html).write_pdf(path)
    return path


def markdown_to_html(markdown: str) -> str:
    lines = markdown.splitlines()
    output: list[str] = []
    in_code = False
    code_lines: list[str] = []
    in_list = False

    def close_list() -> None:
        nonlocal in_list
        if in_list:
            output.append("</ul>")
            in_list = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```"):
            if in_code:
                output.append(f"<pre><code>{html.escape(chr(10).join(code_lines))}</code></pre>")
                code_lines = []
                in_code = False
            else:
                close_list()
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue
        if not stripped:
            close_list()
            continue
        heading = re.match(r"^(#{1,6})\s+(.+)$", stripped)
        if heading:
            close_list()
            level = len(heading.group(1))
            output.append(f"<h{level}>{html.escape(heading.group(2))}</h{level}>")
            continue
        if stripped.startswith("- "):
            if not in_list:
                output.append("<ul>")
                in_list = True
            output.append(f"<li>{html.escape(stripped[2:])}</li>")
            continue
        close_list()
        output.append(f"<p>{html.escape(stripped)}</p>")

    if in_code:
        output.append(f"<pre><code>{html.escape(chr(10).join(code_lines))}</code></pre>")
    close_list()
    return "\n".join(output)


PDF_CSS = """
@page {
  size: A4;
  margin: 2cm;
  @bottom-center {
    content: "Generated by ForgeReport | Page " counter(page);
    color: #8b949e;
    font-size: 9pt;
  }
}
body {
  background: #0d1117;
  color: #e6edf3;
  font-family: "Inter", "Segoe UI", sans-serif;
  font-size: 11pt;
  line-height: 1.55;
}
.cover {
  page-break-after: always;
  min-height: 88vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
}
.brand {
  color: #58a6ff;
  font-size: 18pt;
  font-weight: 700;
  letter-spacing: 0;
}
.cover h1 {
  font-size: 32pt;
  color: #e6edf3;
  margin: 0.5cm 0 0.2cm;
}
.cover p {
  color: #8b949e;
  font-size: 14pt;
}
dl {
  display: grid;
  grid-template-columns: 3cm 1fr;
  gap: 0.15cm 0.5cm;
  margin-top: 1cm;
}
dt {
  color: #58a6ff;
  font-weight: 700;
}
dd {
  margin: 0;
}
h1, h2, h3, h4 {
  color: #58a6ff;
  page-break-after: avoid;
}
h1 {
  font-size: 24pt;
}
h2 {
  border-bottom: 1px solid #30363d;
  padding-bottom: 0.1cm;
  margin-top: 0.8cm;
}
pre {
  background: #161b22;
  color: #79c0ff;
  padding: 0.35cm;
  border-radius: 4px;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
code {
  font-family: "Courier New", monospace;
  font-size: 9pt;
}
li {
  margin-bottom: 0.08cm;
}
a {
  color: #58a6ff;
}
"""
